spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev #開發環境
  application:
    name: springcloudex-config-tony-dev
---
spring:
  profiles: test #測試環境
  application:
    name: springcloudex-config-tony-test
---
#請保存為UTF-8