spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
spring:
  profiles: dev #開發環境(訪問DBclouddb01)
  application:
    name: SpringCloudEx-config-dept-client

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/clouddb01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: tony0204

mybatis:
  mapper-locations: classpath*:mapper/*.xml #MyBatis映射文件的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印


eureka:
  client: #客戶端註冊近eureka服務列表內
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #根據eureka服務端 defaultZone 的配置
      instance:
        instance-id: SpringCloudEx-config-dept8081.com #Status取別名
        prefer-ip-address: true #訪問路徑可以顯示IP
#eureka info
info:
  app.name: org.tony-SpringCloudEx
  company.name: www.tony
  build.artifactId: $project.artifactId$
  buid.version: $project.version$

---
server:
  port: 8001
spring:
  profiles: test #測試環境(訪問DBclouddb02)
  application:
    name: SpringCloudEx-config-dept-client

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13307/clouddb02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: tony0204

mybatis:
  mapper-locations: classpath*:mapper/*.xml #MyBatis映射文件的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印


eureka:
  client: #客戶端註冊近eureka服務列表內
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #根據eureka服務端 defaultZone 的配置
      instance:
        instance-id: SpringCloudEx-config-dept8081.com #Status取別名
        prefer-ip-address: true #訪問路徑可以顯示IP
#eureka info
info:
  app.name: org.tony-SpringCloudEx
  company.name: www.tony
  build.artifactId: $project.artifactId$
  buid.version: $project.version$
---
#請保存為UTF-8